# Workflow name
name: Main

# Build run in each PR
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: buildjet-8vcpu-ubuntu-2204

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'zulu'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Install gradleprofiler and launch
      run: |
        curl -s "https://get.sdkman.io" | bash
        source "/home/runner/.sdkman/bin/sdkman-init.sh"
        sdk install gradleprofiler
        gradle-profiler --benchmark --profile buildscan --project-dir project/android-build-eval/mobile_app1/ --scenario-file performance.scenarios